# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27ab4e124c45446c02fc80007a40462fbba30803b0768b5c1375c0f7563f197431bf6a1def40f3bd01c50337c2c89c4efeec5f17d9a813490ff9c651ec1f5299

test:
  secret_key_base: 6bec69149d1db41e708f52384faa41157e1c83cae4f2f2864d9f5b8f186e3b0128db58205bdacef5af02c195e715776b407d3c051764f07005f70d625ecd72d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
